package org.haifan.merlin.model.gemini.caching;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Code generated by the model that is meant to be executed, and the result returned to the model.
 * <p>
 * Only generated when using the CodeExecution tool, in which the code will be automatically executed, and a corresponding CodeExecutionResult will also be generated.
 * <a href="https://ai.google.dev/api/caching#executablecode">...</a>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExecutableCode {
    private Language language;
    private String code;
}
